# Generated by Django 3.2.18 on 2023-03-08 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('imageURL', models.CharField(blank=True, default='', max_length=100)),
                ('imageFullURL', models.CharField(blank=True, default='', max_length=100)),
                ('imageExtension', models.CharField(blank=True, default='', max_length=50)),
                ('hasAllTeammates', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterComic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('upc', models.CharField(blank=True, default='', max_length=200)),
                ('imageURL', models.CharField(blank=True, default='', max_length=100)),
                ('imageFullURL', models.CharField(blank=True, default='', max_length=100)),
                ('imageExtension', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('characters', models.ManyToManyField(through='characters.CharacterComic', to='characters.Character')),
            ],
        ),
        migrations.AddField(
            model_name='charactercomic',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic', to='characters.comic'),
        ),
        migrations.AlterUniqueTogether(
            name='charactercomic',
            unique_together={('character', 'comic')},
        ),
    ]
